[project]
name = "cifar-100-noisy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mlcroissant>=1.0.12",
    "tensorflow>=2.18.0",
    "tensorflow-datasets>=4.9.7",
]
